---
- name: Add gitlab-runner user to docker group
  user:
    name: gitlab-runner
    append: yes
    groups: docker

- name: Add gitlab-runner user to docker group
  user:
    name: gitlab-runner
    append: yes
    groups: docker

- name: Copy gitlab-runner deb to remote
  copy:
    src: ./files/gitlab-runner_amd64.deb
    dest: /home/ssh-admin

- name: Install gitlab runner
  shell: |
    # curl -LJO https://gitlab-runner-downloads.s3.amazonaws.com/latest/deb/gitlab-runner_amd64.deb
    dpkg -i gitlab-runner_amd64.deb
  args:
    creates: /usr/bin/gitlab-runner

- name: Register gitlab docker runner
  command: |
    gitlab-runner register \
    --non-interactive \
    --url "{{ gitlab_url }}" \
    --registration-token "{{ reg_token }}" \
    --executor "docker" \
    --docker-image alpine:latest \
    --description "docker-runner" \
    --tag-list "docker" \
    --run-untagged="false" \
    --locked="true" \
    --access-level="ref_protected"

- name: Register gitlab shell runner
  command: |
    gitlab-runner register \
    --non-interactive \
    --url "{{ gitlab_url }}" \
    --registration-token "{{ reg_token }}" \
    --executor "shell" \
    --description "shell executor" \
    --tag-list "shell" \
    --run-untagged="false" \
    --locked="true" \
    --access-level="ref_protected"
