---
- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - build-essential
      - python3-pip
    state: present
    update-cache: yes

- name: Immediately update pip
  pip:
    name:
      - pip
    state: latest

- name: Install pip dependencies
  pip:
    name:
      - python-gitlab<=1.12.1

- name: Add gitlab host name
  lineinfile:
    dest: /etc/hosts
    line: "{{ host_ip }} {{ host_name }}"
    state: present
